//
//  Extensions+String.swift
//  catnip
//
//  Created by Diogo Balseiro on 27/12/2025.
//

import Foundation
import SwiftUI
import CryptoKit

/// Generated by Claude

extension String {

    /// Generates a deterministic Color from a string using HSB (Hue, Saturation, Brightness) color space
    /// with SHA256 hashing for optimal color distribution and visual appeal.
    ///
    /// This method creates visually pleasing colors by:
    /// - Using SHA256 cryptographic hashing for excellent distribution across the color spectrum
    /// - Operating in HSB color space for more intuitive color control
    /// - Applying controlled randomness to saturation and brightness for natural variation
    /// - Ensuring deterministic results (same string always produces the same color)
    ///
    /// ## Algorithm Details:
    /// 1. **Hashing**: Uses SHA256 to hash the string's UTF-8 bytes, providing excellent distribution
    /// 2. **Hue Calculation**: First hash byte (0-255) mapped to hue range (0.0-1.0)
    /// 3. **Saturation Variation**: Base saturation ± 10% variation using second hash byte
    /// 4. **Brightness Variation**: Base brightness ± 10% variation using third hash byte
    /// 5. **Clamping**: All values clamped to valid ranges [0.0, 1.0]
    ///
    /// ## Performance Characteristics:
    /// - **Time Complexity**: O(n) where n is string length (due to SHA256 hashing)
    /// - **Memory**: Constant memory usage (~32 bytes for SHA256 hash)
    /// - **Deterministic**: Same input always produces identical output
    /// - **Thread-safe**: No shared state, safe for concurrent access
    ///
    /// ## Visual Quality Benefits:
    /// - **Better Distribution**: SHA256 ensures colors are well-distributed across hue spectrum
    /// - **Consistent Saturation**: Controlled saturation prevents muddy/gray colors
    /// - **Consistent Brightness**: Prevents overly dark or light colors that hurt readability
    /// - **Natural Variation**: Small variations in saturation/brightness create more natural look
    ///
    /// - Parameters:
    ///   - saturation: Base saturation value (0.0-1.0). Higher values produce more vivid colors.
    ///                 Default: 0.7 (70% saturation for balanced vibrancy)
    ///   - brightness: Base brightness value (0.0-1.0). Higher values produce lighter colors.
    ///                 Default: 0.9 (90% brightness for good readability)
    ///   - alpha: Opacity/alpha channel value (0.0-1.0). Default: 1.0 (fully opaque)
    ///
    /// - Returns: A SwiftUI Color with HSB values derived from the string's hash
    ///
    /// ## Parameter Guidelines:
    ///
    /// ### Saturation Values:
    /// - **0.0 - 0.2**: Grayscale/muted colors (good for backgrounds)
    /// - **0.3 - 0.5**: Pastel colors (gentle, easy on eyes)
    /// - **0.6 - 0.8**: Balanced colors (recommended for most UI elements)
    /// - **0.9 - 1.0**: Highly saturated colors (use sparingly, good for accents)
    ///
    /// ### Brightness Values:
    /// - **0.0 - 0.3**: Very dark colors (poor readability with dark text)
    /// - **0.4 - 0.6**: Medium colors (good for backgrounds, check contrast)
    /// - **0.7 - 0.9**: Bright colors (recommended for most uses)
    /// - **0.95 - 1.0**: Very bright colors (excellent for light backgrounds)
    func color(
        saturation: Double = 0.7,
        brightness: Double = 0.9,
        alpha: Double = 1.0
    ) -> Color {
        // Validate input parameters
        precondition(saturation >= 0.0 && saturation <= 1.0, "Saturation must be between 0.0 and 1.0")
        precondition(brightness >= 0.0 && brightness <= 1.0, "Brightness must be between 0.0 and 1.0")
        precondition(alpha >= 0.0 && alpha <= 1.0, "Alpha must be between 0.0 and 1.0")
        
        // Generate SHA256 hash from string's UTF-8 representation
        // SHA256 provides excellent distribution properties compared to simple hash functions
        let hash = SHA256.hash(data: self.data(using: .utf8) ?? Data())
        let hashBytes = Array(hash)
        
        // Extract hue from first hash byte (0-255 mapped to 0.0-1.0)
        // This gives us the primary color characteristic
        let hue = Double(hashBytes[0]) / 255.0
        
        // Add controlled variation to saturation using second hash byte
        // Variation range: ±10% of base saturation for natural color diversity
        let saturationVariation = (Double(hashBytes[1]) / 255.0 - 0.5) * 0.2 // Range: -0.1 to +0.1
        let finalSaturation = saturation + saturationVariation
        
        // Add controlled variation to brightness using third hash byte
        // Variation range: ±10% of base brightness for subtle lighting differences
        let brightnessVariation = (Double(hashBytes[2]) / 255.0 - 0.5) * 0.2 // Range: -0.1 to +0.1
        let finalBrightness = brightness + brightnessVariation
        
        // Clamp all values to valid [0.0, 1.0] range to prevent invalid colors
        return Color(
            hue: hue, // No clamping needed - already in [0.0, 1.0]
            saturation: max(0.0, min(1.0, finalSaturation)),
            brightness: max(0.0, min(1.0, finalBrightness)),
            opacity: alpha
        )
    }
}

// MARK: - Specialized Color Variants

extension String {
    
    /// Generates a pastel color variant optimized for gentle, soothing UI elements.
    ///
    /// Pastel colors are characterized by low saturation (30%) and high brightness (95%),
    /// making them ideal for backgrounds, subtle highlights, and calming UI elements.
    ///
    var pastelColor: Color {
        
        return self.color(saturation: 0.3, brightness: 0.95)
    }
    
    /// Generates a vibrant color variant optimized for attention-grabbing UI elements.
    ///
    /// Vibrant colors feature high saturation (90%) and medium-high brightness (80%),
    /// making them perfect for buttons, important indicators, and focal points.
    var vibrantColor: Color {
        
        return self.color(saturation: 0.9, brightness: 0.8)
    }
}
